version: "3"

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: falcaof14/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile.prod
    image: falcaof14/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
